### ISSUE TITLE
Complete Sinequa Useability Analysis

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/planetary-data-engine#5]
## 💡 Description

We have remaining question before we can validate that sinequa can work for PDS:

- [x] how to use sinequa through a web API, 
- [x] enable specific facets, 
- [x] sort the results

Sub-tasks:
- #8

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 has access to the online documentation and all answers should be yes, but this requires some work to actually enable this items (api end-point, facetting, ...).

Joe experiments with it in the sandbox.

**Comment by tloubrieu-jpl** [comment]
There is no way of directly expose the sinequa search end point but there is an angular framework search based application.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 is waiting for support to create an API end-point (with Angular).

Some progress on the analysis of the facets and sort features.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 received an example jupyter notebook which uses the API of sinequa.

**Comment by tloubrieu-jpl** [comment]
@jjacob7734 was able to make the jupyter notebook work on our sandbox deployment.
For now it requires credential to connect to the API.

For the web we would need anonymous access.

**Comment by jordanpadams** [comment]
📆 September status: Analysis nearing completion. Should be wrapped up with presentation at next sprint review. Onto test suite.
